# Change these first
owner: RKTowse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: OFI
    url: https://www.ofi.ca
  - name: CEOTR
    url: https://ceotr.ocean.dal.ca
  - name: Rundeck
    url: https://rundeck.ceotr.ca/menu/home
  - name: data.ceotr.ca
    check: "tcp-ping"
    url: data.ceotr.ca
    port: 53
  - name: porky.ocean.dal.ca
    check: "tcp-ping"
    url: porky.ocean.dal.ca
    port: 53
  - name: prod.ceotr.ca
    check: "tcp-ping"
    url: prod.ceotr.ca
    port: 53

    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
